 
name: 'chaoxing'

on:
  push:
    branches: 
      - master
  schedule:
    - cron: '*/1 * * * *'

jobs:
  get_points:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v2
    - name: 'Setup python'
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: 'Install dependencies'
      run: python -m pip install --upgrade requests
    - name: 'Qiandao'
      env:
        CHAOXING_USERNAME: ${{ secrets.CHAOXING_USERNAME }}
        CHAOXING_PASSWORD: ${{ secrets.CHAOXING_PASSWORD }}
        CHAOXING_SCHOOL: ${{ secrets.CHAOXING_SCHOOL }}
        CHAOXING_SERVER: ${{ secrets.CHAOXING_SERVER }}
        CHAOXING_SERVEROR: ${{ secrets.CHAOXING_SERVEROR }}
      run: python cx.py
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
